{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "296\n"
     ]
    },
    {
     "ename": "RayTaskError(RuntimeError)",
     "evalue": "\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n    raise RuntimeError(\nRuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n\n\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n    function = pickle.loads(serialized_function)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n    self.ant_env = AntEnv(\n                   ^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n    MujocoEnv.__init__(\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n    self.model, self.data = self._initialize_simulation()\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n    model = mujoco.MjModel.from_xml_path(self.fullpath)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.4926093.xml'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayTaskError(RuntimeError)\u001b[0m                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[6], line 189\u001b[0m\n\u001b[0;32m    186\u001b[0m         np\u001b[38;5;241m.\u001b[39msave(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparentbcs\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(experiments), parentbcs)\n\u001b[0;32m    187\u001b[0m    env\u001b[38;5;241m.\u001b[39mclose()\n\u001b[1;32m--> 189\u001b[0m \u001b[43mmain\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    191\u001b[0m \u001b[38;5;66;03m# isprobati crossover bez obzira na sparsity rate\u001b[39;00m\n\u001b[0;32m    192\u001b[0m \n\u001b[0;32m    193\u001b[0m \u001b[38;5;66;03m#x = np.load(\"bestsolution7.npy\")\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    199\u001b[0m \u001b[38;5;66;03m#for param in policy.parameters():\u001b[39;00m\n\u001b[0;32m    200\u001b[0m \u001b[38;5;66;03m#   print(param)\u001b[39;00m\n",
      "Cell \u001b[1;32mIn[6], line 145\u001b[0m, in \u001b[0;36mmain\u001b[1;34m()\u001b[0m\n\u001b[0;32m    143\u001b[0m allmembers \u001b[38;5;241m=\u001b[39m policies\u001b[38;5;241m+\u001b[39moffspring\n\u001b[0;32m    144\u001b[0m \u001b[38;5;66;03m#print(len(allmembers))\u001b[39;00m\n\u001b[1;32m--> 145\u001b[0m bcs \u001b[38;5;241m=\u001b[39m \u001b[43mbc_a_set_of_policies\u001b[49m\u001b[43m(\u001b[49m\u001b[43mallmembers\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[0;32m    146\u001b[0m allbcs\u001b[38;5;241m.\u001b[39mappend(allmembers[\u001b[38;5;241m0\u001b[39m])\n\u001b[0;32m    147\u001b[0m parentbcs\u001b[38;5;241m.\u001b[39mappend(allmembers)\n",
      "Cell \u001b[1;32mIn[6], line 96\u001b[0m, in \u001b[0;36mbc_a_set_of_policies\u001b[1;34m(policies, pseudo)\u001b[0m\n\u001b[0;32m     95\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mbc_a_set_of_policies\u001b[39m(policies, pseudo\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m):\n\u001b[1;32m---> 96\u001b[0m   \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mray\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[43m[\u001b[49m\u001b[43mget_bc_policy\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mremote\u001b[49m\u001b[43m(\u001b[49m\u001b[43mi\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpseudo\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mi\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mpolicies\u001b[49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py:21\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;129m@wraps\u001b[39m(fn)\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mauto_init_wrapper\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[0;32m     20\u001b[0m     auto_init_ray()\n\u001b[1;32m---> 21\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    101\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m!=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minit\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mor\u001b[39;00m is_client_mode_enabled_by_default:\n\u001b[0;32m    102\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mgetattr\u001b[39m(ray, func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 103\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\worker.py:2772\u001b[0m, in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   2766\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m   2767\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mInvalid type of object refs, \u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mtype\u001b[39m(object_refs)\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, is given. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2768\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mobject_refs\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m must either be an ObjectRef or a list of ObjectRefs. \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   2769\u001b[0m     )\n\u001b[0;32m   2771\u001b[0m \u001b[38;5;66;03m# TODO(ujvl): Consider how to allow user to retrieve the ready objects.\u001b[39;00m\n\u001b[1;32m-> 2772\u001b[0m values, debugger_breakpoint \u001b[38;5;241m=\u001b[39m \u001b[43mworker\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_objects\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobject_refs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   2773\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i, value \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28menumerate\u001b[39m(values):\n\u001b[0;32m   2774\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, RayError):\n",
      "File \u001b[1;32mc:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\worker.py:919\u001b[0m, in \u001b[0;36mWorker.get_objects\u001b[1;34m(self, object_refs, timeout, return_exceptions, skip_deserialization)\u001b[0m\n\u001b[0;32m    917\u001b[0m     global_worker\u001b[38;5;241m.\u001b[39mcore_worker\u001b[38;5;241m.\u001b[39mdump_object_store_memory_usage()\n\u001b[0;32m    918\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, RayTaskError):\n\u001b[1;32m--> 919\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m value\u001b[38;5;241m.\u001b[39mas_instanceof_cause()\n\u001b[0;32m    920\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    921\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m value\n",
      "\u001b[1;31mRayTaskError(RuntimeError)\u001b[0m: \u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n    raise RuntimeError(\nRuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n\n\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n    function = pickle.loads(serialized_function)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n    self.ant_env = AntEnv(\n                   ^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n    MujocoEnv.__init__(\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n    self.model, self.data = self._initialize_simulation()\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n    model = mujoco.MjModel.from_xml_path(self.fullpath)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.4926093.xml'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-02-19 17:06:43,789\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,789\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,796\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,796\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,796\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,801\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,805\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,807\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,809\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,811\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,813\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,815\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,817\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,819\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,820\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,823\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,826\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:43,828\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=20676, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981198.2283862.xml'\n",
      "2025-02-19 17:06:48,838\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.4926093.xml'\n",
      "2025-02-19 17:06:48,838\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.4926093.xml'\n",
      "2025-02-19 17:06:48,838\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n",
      "2025-02-19 17:06:48,842\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.4926093.xml'\n",
      "2025-02-19 17:06:48,844\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n",
      "2025-02-19 17:06:48,846\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n",
      "2025-02-19 17:06:48,848\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n",
      "2025-02-19 17:06:48,850\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n",
      "2025-02-19 17:06:48,852\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n",
      "2025-02-19 17:06:48,853\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=5008, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.4926093.xml'\n",
      "2025-02-19 17:06:48,855\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 298, in f\n",
      "    raise RuntimeError(\n",
      "RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment or cannot be found from sys.path ['c:\\\\Users\\\\bgasp\\\\Desktop\\\\gecco_worksop', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\thirdparty_files', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\ray\\\\_private\\\\workers', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\python312.zip', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\DLLs', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\win32\\\\lib', 'c:\\\\Users\\\\bgasp\\\\miniconda3\\\\envs\\\\gymenv3\\\\Lib\\\\site-packages\\\\Pythonwin']:\n",
      "\n",
      "\u001b[36mray::get_bc_policy()\u001b[39m (pid=8492, ip=127.0.0.1)\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "    function = pickle.loads(serialized_function)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\utils\\ezpickle.py\", line 36, in __setstate__\n",
      "    out = type(self)(*d[\"_ezpickle_args\"], **d[\"_ezpickle_kwargs\"])\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium_robotics\\envs\\maze\\ant_maze_v4.py\", line 62, in __init__\n",
      "    self.ant_env = AntEnv(\n",
      "                   ^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\ant_v4.py\", line 79, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 78, in __init__\n",
      "    self.model, self.data = self._initialize_simulation()\n",
      "                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\bgasp\\miniconda3\\envs\\gymenv3\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 128, in _initialize_simulation\n",
      "    model = mujoco.MjModel.from_xml_path(self.fullpath)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ValueError: mjParseXML: empty file 'C:\\Users\\bgasp\\AppData\\Local\\Temp\\ant_maze1739981203.5664542.xml'\n"
     ]
    }
   ],
   "source": [
    "'Paper - code'\n",
    "\n",
    "import gymnasium as gym\n",
    "import gymnasium_robotics\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "import numpy as np\n",
    "import time\n",
    "import copy\n",
    "import random\n",
    "from collections import Counter, deque\n",
    "#from shapely.geometry import Point, MultiPoint\n",
    "#from shapely.geometry.polygon import Polygon\n",
    "import ray\n",
    "\n",
    "gym.register_envs(gymnasium_robotics)\n",
    "\n",
    "env = gym.make(\"AntMaze_UMaze-v4\")\n",
    "\n",
    "#ray.init()\n",
    "\n",
    "class Policy(nn.Module):\n",
    "  #torch.manual_seed(191)\n",
    "  def __init__(self):\n",
    "      super(Policy, self).__init__()\n",
    "      self.affine1 = nn.Linear(27,8)\n",
    "      #self.affine2 = nn.Linear(32,32)\n",
    "      self.action_head = nn.Linear(8,8)\n",
    "      self.weights_initialization()\n",
    "      self.setnogradient()\n",
    "  def setnogradient(self):\n",
    "    for param in self.parameters():\n",
    "        param.requires_grad = False  \n",
    "  def forward(self, inputs):\n",
    "      x = inputs\n",
    "      x = F.relu(self.affine1(x))\n",
    "      #x = F.relu(self.affine2(x))\n",
    "      return F.tanh(self.action_head(x))\n",
    "  def weights_initialization(self):\n",
    "      for m in self.modules():\n",
    "          #print(m)\n",
    "          #torch.manual_seed(191)\n",
    "          if isinstance(m, nn.Linear):\n",
    "              nn.init.xavier_normal_(m.weight)\n",
    "              nn.init.constant_(m.bias, 0)\n",
    "  def shapes_per_layer(self):\n",
    "      return [list(p.data.shape) for p in self.parameters()]\n",
    "  def count_parameters(self):\n",
    "      return sum(p.numel() for p in self.parameters())\n",
    "\n",
    "niche_real_counter = Counter()\n",
    "\n",
    "@ray.remote\n",
    "def get_bc_policy(policy, pseudo=False):\n",
    "    #global INDIVIDUAL_COUNTER\n",
    "    #INDIVIDUAL_COUNTER += 1\n",
    "    observation, info = env.reset(seed=42)\n",
    "    #print(info)\n",
    "    #print(type(observation[\"observation\"]))\n",
    "    #sum_or_rewards = 0\n",
    "    for _ in range(1000):\n",
    "        #action = env.action_space.sample()\n",
    "        observation = torch.tensor(observation[\"observation\"], dtype=torch.float32)\n",
    "        #print(torch.randn(17))\n",
    "        #if pseudo:\n",
    "         #   seeds = np.random.randint(0,27,7)\n",
    "          #  observation[seeds[0]] = 0\n",
    "           # observation[seeds[1]] = 0\n",
    "           # observation[seeds[2]] = 0\n",
    "           # observation[seeds[3]] = 0\n",
    "           # observation[seeds[4]] = 0\n",
    "           # observation[seeds[5]] = 0\n",
    "           # observation[seeds[6]] = 0\n",
    "        action = policy(observation).detach().numpy()\n",
    "        if pseudo:\n",
    "            seeds = np.random.randint(0,3,3)\n",
    "            action[seeds[0]] = 0\n",
    "            action[seeds[1]] = 0\n",
    "            action[seeds[2]] = 0\n",
    "        #print(action)\n",
    "        observation, reward, terminated, truncated, info = env.step(action)\n",
    "        #sum_or_rewards += reward\n",
    "        #if terminated or truncated:\n",
    "    bc1 = observation[\"achieved_goal\"][0]\n",
    "    bc2 = observation[\"achieved_goal\"][1]\n",
    "    bc = np.array([bc1, bc2])\n",
    "    #if random.random() < 0.95:\n",
    "    archivebc.append(bc)\n",
    "    return bc\n",
    "\n",
    "#def test_a_set_of_policies(policies):\n",
    "#   return [test_policy(i) for i in policies]\n",
    "\n",
    "def bc_a_set_of_policies(policies, pseudo=False):\n",
    "  return ray.get([get_bc_policy.remote(i, pseudo) for i in policies])\n",
    "\n",
    "dist = lambda p1, p2: np.sqrt(((p1-p2)**2).sum())\n",
    "\n",
    "def get_fitnessess(xy_list, K=15):\n",
    "   dm = np.asarray([[dist(p1, p2) for p2 in xy_list+archivebc] for p1 in xy_list+archivebc])\n",
    "   dm.sort(axis=1)\n",
    "   #print(dm)\n",
    "   #print(dm[:,:(K+1)].sum(axis=1))\n",
    "   return dm[:(POPULATION_SIZE+N_OF_OFFSPRING),:(K+1)].sum(axis=1)\n",
    "\n",
    "def get_distance_from_parent_fitnesses(bcs):\n",
    "    return [np.linalg.norm(bcs[i]-bcs[0]) for i in range(0,len(bcs))]\n",
    "\n",
    "def mutate(agent):\n",
    "    child_agent = copy.deepcopy(agent)\n",
    "    mutation_power = 1\n",
    "    for param in child_agent.parameters():\n",
    "        if(len(param.shape)==2):\n",
    "            for i0 in range(param.shape[0]):\n",
    "                for i1 in range(param.shape[1]):\n",
    "                    if random.random() > 0:\n",
    "                        param[i0][i1]+= mutation_power * np.random.normal(0.1)\n",
    "        elif(len(param.shape)==1):\n",
    "            for i0 in range(param.shape[0]):\n",
    "                if random.random() > 0:\n",
    "                    param[i0]+=mutation_power * np.random.normal(0.1)\n",
    "    return child_agent\n",
    "\n",
    "POPULATION_SIZE = 1\n",
    "N_OF_OFFSPRING = 50\n",
    "archive_genotype = []\n",
    "archivebc = []\n",
    "\n",
    "policy = Policy()\n",
    "print(policy.count_parameters())\n",
    "\n",
    "def main():\n",
    "   for experiments in range(3):\n",
    "        N_GENERATIONS = 5\n",
    "        policies = [Policy() for i in range(POPULATION_SIZE)]\n",
    "        allbcs = []\n",
    "        parentbcs = []\n",
    "        for generation in range(N_GENERATIONS):\n",
    "            #parent_bc = get_bc_policy.remote(policies[0])\n",
    "            #print([parent_bc],11) \n",
    "            offspring = [mutate(random.choice(policies)) for i in range(N_OF_OFFSPRING)] \n",
    "            allmembers = policies+offspring\n",
    "            #print(len(allmembers))\n",
    "            bcs = bc_a_set_of_policies(allmembers, False)\n",
    "            allbcs.append(allmembers[0])\n",
    "            parentbcs.append(allmembers)\n",
    "            #bc_a_set_of_policies(allmembers, False)\n",
    "            #print(bcs) \n",
    "            for i in bcs:\n",
    "                    niche_real_number = int(np.floor(i)[0]*10+np.floor(i)[1])\n",
    "                    niche_real_counter.update([niche_real_number])\n",
    "            bc_a_set_of_policies(policies, False)\n",
    "            print(niche_real_counter)\n",
    "            print(len(niche_real_counter))\n",
    "            #pseudobcs = bc_a_set_of_policies(allmembers, True)\n",
    "            #print(\"Niches visited: {}\".format(len(niche_counter)))\n",
    "            #print(pseudo_bcs)\n",
    "            #fitnesses = get_fitnessess(bcs)\n",
    "            fitnesses = get_distance_from_parent_fitnesses(bcs)\n",
    "            #print(fitnesses)\n",
    "            #print(fitnesses)\n",
    "            surviving_indices = np.argsort(fitnesses)[::-1][:POPULATION_SIZE]\n",
    "            #print(surviving_indices)\n",
    "            #print(surviving_indices)\n",
    "            policies = [allmembers[i] for i in surviving_indices]\n",
    "            #fitnesses = test_a_set_of_policies(policies)\n",
    "            #print(fitnesses)\n",
    "            #print(max(fitnesses))\n",
    "            #print(archive)\n",
    "            #print(len(archive))\n",
    "            #print(archive_genotype)\n",
    "            #print(len(archive))\n",
    "            #print([archive_genotype[i] for i in np.random.randint(0,len(archive_genotype),POPULATION_SIZE//2)])\n",
    "            #archivedbc = []\n",
    "            #print(parent_indices)\n",
    "            #parent_genotypes_post = [crossover(parent_genotypes[np.random.randint(POPULATION_SIZE)],parent_genotypes[np.random.randint(POPULATION_SIZE)]) for i in range(POPULATION_SIZE)]\n",
    "            #elite_policy = copy.deepcopy(policies[parent_indices[0]])\n",
    "            #print([policies[i].get_genotype() for i in parent_indices])\n",
    "            #policies = generate_N_initial_policies(POPULATION_SIZE, 0.5, parent_genotypes)\n",
    "            #policies[0] = elite_policy\n",
    "            #print(np.all(parent_genotypes[6]==parent_genotypes[9]))\n",
    "            #print(\"SVE OK\")\n",
    "            print(\"End of generation {}, experiment {}\".format(generation+1,experiments+1))\n",
    "        np.save(\"allbcs{}\".format(experiments), allbcs)\n",
    "        np.save(\"parentbcs{}\".format(experiments), parentbcs)\n",
    "   env.close()\n",
    "\n",
    "main()\n",
    "\n",
    "# isprobati crossover bez obzira na sparsity rate\n",
    "\n",
    "#x = np.load(\"bestsolution7.npy\")\n",
    "#print(x)\n",
    "#policy = Policy(0.5,x)\n",
    "#fitness = get_bc_policy(policy)\n",
    "#print(fitness)\n",
    "\n",
    "#for param in policy.parameters():\n",
    "#   print(param)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gymenv3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
